### ISSUE TITLE
Define UseCase Model

### ISSUE THREAD

**Issue by lucaschagas** [toacy/cos482-ple#5]

**Comment by lucaschagas** [comment]
Propostas iniciais e futuras alterações aos casos de uso estão disponíveis na seguinte página da wiki: https://github.com/toacy/cos482-ple/wiki/UseCase

**Comment by gxara** [comment]
- [ ] Verificar a qualidade dos casos de uso utilizando o checklist a ser enviado pelo professor
- [ ] Alterar o item 9 de inscrição em disciplinas para include
